### ISSUE TITLE
Python installed with brew doesn't require sudo to install ohmu

### ISSUE THREAD

**Issue by AlexSwensen** [paul-nechifor/ohmu#30]
If you installed python or python3 with `brew` on OSX, running pip with `sudo` can cause permission issues that can otherwise be avoided. OSX users should not need to use sudo to install ohmu.

**Comment by paul-nechifor** [comment]
@AlexSwensen Is this okay?

**Comment by AlexSwensen** [comment]
Yeah, thats generally better practice. :-)
Thanks! :-)
