### ISSUE TITLE
Add filesize next to filename

### ISSUE THREAD

**Issue by paul-nechifor** [paul-nechifor/ohmu#6]

**Comment by alphapapa** [comment]
Can't wait for this.  :)  I use the Konqueror File Size View when I need to, but if ohmu would show the size of files and directories (plus children) next to the filename, it could be used instead.

**Comment by alphapapa** [comment]
I just updated and tested this, and it's working great!  I love the way it gives quick feedback as it continues scanning deeper.  Great work.
